### ISSUE TITLE
Mention Homebrew in docs

### ISSUE THREAD

**Issue by cseelus** [yihui/homebrew-tinytex#1]
Found this repo by chance, imho this is the most convenient way for macOS users to install. 

Is there a reason why the homebrew formula isn't mentioned in the [docs](https://yihui.name/tinytex/)?

**Comment by yihui** [comment]
This way is convenient but in fact much more complicated behind the scenes. See FAQ 15: https://yihui.name/tinytex/faq/

**Comment by cseelus** [comment]
Thanks for info!
